### ISSUE TITLE
Feature : return channel id in order to prepare new API version

### ISSUE THREAD

**Issue by Nerothos** [jrm780/gotirc#1]
First, thank you for creating this project 👍 

In order to prepare the use of the new API version (or even using the V5 the "right" way), it would be nice to add the channel_id to all method returning the channel name at the moment (like client.OnChat).

Cheers.

**Comment by jrm780** [comment]
No problem! Glad you're finding this project useful :)

According to the [Twitch Chat and IRC Documentation](https://dev.twitch.tv/docs/irc), the channel_id or `room-id` is included in most tags already. For example:

```go
client.OnChat(func(channel string, tags map[string]string, msg string) {
	fmt.Println("Channel Name:", channel)
	fmt.Println("Channel ID:", tags["room-id"])
})
```

should give you what you're looking for. I feel that adding the channel ID to the callback parameters would be redundant right now (perhaps this will change in the future), as it's already available in the tags. The channel name is not a part of the tags supplied by Twitch servers in their IRC messages, so it's passed to the callback separately.

Please let me know if this makes sense or whether you disagree, in which case we can take a closer look at it!

**Comment by Nerothos** [comment]
Hi, thanks for replying.

Ah yes I didn't think of the tags (I'm still a little with tmi.js on the mind x)). I understand your thinking and it indeed make sense to not include it in the callback as long as we are sure that all tags (for each function) contains it ;)

Thanks again
